name: Renovate
on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      dryRun:
        type: choice
        description: "Dry-Run"
        default: "false"
        options:
          - "true"
          - "false"
      logLevel:
        type: choice
        description: "Log-Level"
        default: "debug"
        options:
          - "info"
          - "debug"
          - "trace"
  # Scheduled runs (checks for updates every Monday at 7:00am UTC)
  schedule:
    - cron: '0 7 * * 1'
  # Run on pushes to renovate config
  push:
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  DRY_RUN: "${{ inputs.dryRun == 'true' }}"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          # Repository taken from variable to keep this workflow generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          # Username for Git commits
          RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
          # Use GitHub API to create commits
          RENOVATE_PLATFORM: "github"
          # Include logs in PR description
          RENOVATE_PR_FOOTER: "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate)."
          # Limit Git history for performance
          RENOVATE_GIT_NO_VERIFY: "['commit-msg','pre-commit']"
          # Set log level
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          # Set dry run mode
          RENOVATE_DRY_RUN: ${{ env.DRY_RUN }}